apiVersion: apps/v1
kind: Deployment
metadata:
  name: enquiry-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.enquiry.replicas }}
  selector:
    matchLabels:
      app: enquiry-service
  template:
    metadata:
      labels:
        app: enquiry-service
    spec:
      containers:
      - name: enquiry-service
        image: {{ .Values.enquiry.image }}
        ports:
        - containerPort: {{ .Values.enquiry.port }}
        command: ["python", "-m", "http.server", "5001"]
        envFrom:
        - configMapRef:
            name: student-config
        - secretRef:
            name: student-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: enquiry-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: enquiry-service
  ports:
  - port: {{ .Values.enquiry.port }}
    targetPort: {{ .Values.enquiry.port }}